/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_customview_ndk_jni */

#ifndef _Included_com_customview_ndk_jni
#define _Included_com_customview_ndk_jni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_customview_ndk_jni
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_customview_ndk_jni_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
